import importlib.util
import os
from pathlib import Path
import subprocess
import sys
import tempfile
import unittest


ROOT = Path(__file__).resolve().parents[1]
RENDERER = ROOT / "deploy" / "render_yuelei_test_nginx.py"
SOURCE = ROOT / "deploy" / "nginx-huangquechuanmei.conf"


def load_renderer():
    spec = importlib.util.spec_from_file_location("render_yuelei_test_nginx", RENDERER)
    module = importlib.util.module_from_spec(spec)
    assert spec.loader is not None
    spec.loader.exec_module(module)
    return module


class YueleiTestDomainNginxTests(unittest.TestCase):
    @classmethod
    def setUpClass(cls):
        cls.renderer = load_renderer()
        cls.source = SOURCE.read_text(encoding="utf-8")

    def test_rendered_vhost_directly_serves_test_runtime(self):
        rendered = self.renderer.render_config(self.source)
        self.assertIn("server_name yuelei.huangquechuanmei.com;", rendered)
        self.assertIn("root /var/www/huangquechuanmei;", rendered)
        self.assertIn("location ^~ /api/gen/", rendered)
        self.assertIn("location ^~ /api/auth/", rendered)
        self.assertIn("location ^~ /api/admin/", rendered)
        self.assertIn("proxy_set_header Host $host;", rendered)
        self.assertIn("/etc/letsencrypt/live/yuelei.huangquechuanmei.com/", rendered)

    def test_rendered_vhost_cannot_reenter_production_virtual_host(self):
        rendered = self.renderer.render_config(self.source)
        forbidden = (
            "proxy_pass https://127.0.0.1",
            "proxy_ssl_name huangquechuanmei.com",
            "proxy_set_header Host huangquechuanmei.com",
            "proxy_redirect https://huangquechuanmei.com",
            "server_name huangquechuanmei.com www.huangquechuanmei.com;",
            "/etc/letsencrypt/live/huangquechuanmei.com/",
        )
        for marker in forbidden:
            with self.subTest(marker=marker):
                self.assertNotIn(marker, rendered)

    def test_http_redirect_and_clean_url_redirect_stay_on_test_origin(self):
        rendered = self.renderer.render_config(self.source)
        self.assertIn(
            "return 301 https://yuelei.huangquechuanmei.com$request_uri;",
            rendered,
        )
        self.assertIn("return 301 /$1$is_args$args;", rendered)
        self.assertNotIn("https://huangquechuanmei.com$request_uri", rendered)

    def test_renderer_fails_closed_when_reviewed_source_contract_drifts(self):
        damaged = self.source.replace(
            "location ^~ /api/auth/", "location ^~ /api/auth-broken/", 1
        )
        with self.assertRaisesRegex(self.renderer.RenderError, "missing"):
            self.renderer.render_config(damaged)

    def test_cli_writes_complete_config_atomically(self):
        with tempfile.TemporaryDirectory() as directory:
            output = Path(directory) / "yuelei-test.conf"
            subprocess.run(
                [
                    sys.executable,
                    str(RENDERER),
                    "--source",
                    str(SOURCE),
                    "--output",
                    str(output),
                ],
                check=True,
            )
            rendered = output.read_text(encoding="utf-8")
            self.assertTrue(rendered.startswith("# Generated by"))
            if os.name == "posix":
                self.assertEqual(0o644, output.stat().st_mode & 0o777)
            self.assertNotIn(".yuelei-test.conf.", " ".join(p.name for p in output.parent.iterdir()))


if __name__ == "__main__":
    unittest.main()
