#!/usr/bin/env python3
"""Render the Yuelei test-domain vhost from the reviewed main-site vhost."""

from __future__ import annotations

import argparse
import os
from pathlib import Path
import tempfile


PRODUCTION_NAMES = "server_name huangquechuanmei.com www.huangquechuanmei.com;"
TEST_NAME = "yuelei.huangquechuanmei.com"
PRODUCTION_CERT = "/etc/letsencrypt/live/huangquechuanmei.com/"
TEST_CERT = f"/etc/letsencrypt/live/{TEST_NAME}/"


class RenderError(RuntimeError):
    pass


def _server_blocks(source: str) -> list[str]:
    lines = source.splitlines(keepends=True)
    blocks: list[str] = []
    index = 0
    while index < len(lines):
        if lines[index].strip() != "server {":
            index += 1
            continue
        start = index
        depth = 0
        while index < len(lines):
            line = lines[index]
            depth += line.count("{") - line.count("}")
            index += 1
            if depth == 0:
                blocks.append("".join(lines[start:index]))
                break
        else:
            raise RenderError("source contains an unterminated server block")
    return blocks


def render_config(source: str) -> str:
    candidates = [
        block
        for block in _server_blocks(source)
        if PRODUCTION_NAMES in block and "listen 443 ssl" in block
    ]
    if len(candidates) != 1:
        raise RenderError(
            "expected exactly one reviewed production HTTPS server block, "
            f"found {len(candidates)}"
        )

    https = candidates[0]
    required = (
        "root /var/www/huangquechuanmei;",
        "location ^~ /api/gen/",
        "location ^~ /api/auth/",
        "location ^~ /api/admin/",
        "location / {",
        PRODUCTION_CERT,
    )
    missing = [marker for marker in required if marker not in https]
    if missing:
        raise RenderError("source server block is missing: " + ", ".join(missing))

    https = https.replace(PRODUCTION_NAMES, f"server_name {TEST_NAME};", 1)
    https = https.replace(PRODUCTION_CERT, TEST_CERT)
    # 测试服与主站 vhost 共存于同一 Nginx：[::]:443 的 socket 选项（ipv6only）
    # 全进程只能声明一次，主站 block 已声明。渲染结果必须去掉，否则 nginx -t
    # 报 duplicate listen options。nginx 对 [::] 监听默认即 ipv6only=on，行为不变。
    https = https.replace("listen [::]:443 ssl ipv6only=on;", "listen [::]:443 ssl;")
    https = https.replace(
        "/var/log/nginx/huangquechuanmei.access.log",
        "/var/log/nginx/yuelei.huangquechuanmei.access.log",
    )
    https = https.replace(
        "/var/log/nginx/huangquechuanmei.error.log",
        "/var/log/nginx/yuelei.huangquechuanmei.error.log",
    )

    forbidden = (
        "proxy_pass https://127.0.0.1",
        "proxy_ssl_name huangquechuanmei.com",
        "proxy_set_header Host huangquechuanmei.com",
        "proxy_redirect https://huangquechuanmei.com",
        PRODUCTION_NAMES,
        PRODUCTION_CERT,
    )
    present = [marker for marker in forbidden if marker in https]
    if present:
        raise RenderError("rendered HTTPS block retained forbidden markers: " + ", ".join(present))

    http = f"""server {{
    listen 80;
    listen [::]:80;
    server_name {TEST_NAME};

    location ^~ /.well-known/acme-challenge/ {{
        root /var/www/acme;
        default_type text/plain;
        try_files $uri =404;
    }}

    location / {{
        return 301 https://{TEST_NAME}$request_uri;
    }}
}}
"""
    return (
        "# Generated by deploy/render_yuelei_test_nginx.py. Do not edit on the server.\n"
        "# The HTTPS vhost directly serves the test runtime and preserves the public Host.\n\n"
        + http
        + "\n"
        + https
    )


def _atomic_write(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    fd, temporary = tempfile.mkstemp(prefix=f".{path.name}.", dir=str(path.parent))
    try:
        with os.fdopen(fd, "w", encoding="utf-8", newline="\n") as handle:
            handle.write(content)
            handle.flush()
            os.fsync(handle.fileno())
        os.chmod(temporary, 0o644)
        os.replace(temporary, path)
    except BaseException:
        try:
            os.unlink(temporary)
        except FileNotFoundError:
            pass
        raise


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--source",
        type=Path,
        default=Path(__file__).with_name("nginx-huangquechuanmei.conf"),
    )
    parser.add_argument("--output", type=Path, required=True)
    args = parser.parse_args()
    rendered = render_config(args.source.read_text(encoding="utf-8"))
    _atomic_write(args.output, rendered)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
